const arabic = {
  // Existing keys from previous components
  lang: "En",
  home: "الرئيسية",
  menu: "القائمة",
  reservation: "الحجز",
  contactUs: "اتصل بنا",
  myOrders: "طلباتي",
  signIn: "تسجيل الدخول",
  register: "إنشاء حساب",
  logout: "تسجيل الخروج",
  wishlist: "المفضلة",
  cart: "عربة التسوق",
  chatWith: "الدردشة مع الإدارة",
  noMessages: "لا توجد رسائل بعد. ابدأ المحادثة!",
  typeMessage: "اكتب رسالتك...",
  sendButton: "إرسال",

  // AdminDashboard
  adminDashboard: "لوحة تحكم الإدارة",
  orders: "الطلبات",
  reservations: "الحجوزات",
  menu: "القائمة",
  chat: "الدردشة",
  logout: "تسجيل الخروج",
  loading: "جارٍ التحميل...",
  routeNotFound: "المسار غير موجود: {pathname}",
  logoutSuccess: "تم تسجيل الخروج بنجاح!",
  logoutFailed: "فشل في تسجيل الخروج: {error}",

  // AdminOrdersPage
  ordersManagement: "إدارة الطلبات",
  sort: "ترتيب:",
  sortNewest: "الأحدث أولاً",
  sortOldest: "الأقدم أولاً",
  status: "الحالة:",
  statusAll: "الكل",
  statusPending: "معلق",
  statusAccepted: "مقبول",
  statusRejected: "مرفوض",
  payment: "الدفع:",
  paymentAll: "الكل",
  paymentCod: "الدفع عند الاستلام",
  paymentPaypal: "باي بال",
  noOrdersFiltered: "لا توجد طلبات تطابق الفلاتر المحددة.",
  success: "نجاح!",
  error: "خطأ!",
  orderAccepted: "تم قبول الطلب #{orderId}",
  orderUpdateFailed: "فشل في تحديث الطلب: {error}",
  deleteOrderConfirmTitle: "هل أنت متأكد؟",
  deleteOrderConfirmText: "حذف الطلب #{orderId}؟",
  deleteOrderConfirmButton: "نعم، احذف!",
  deleteOrderSuccessTitle: "تم الحذف!",
  deleteOrderSuccessMessage: "تم حذف الطلب #{orderId}",
  clearAllOrdersConfirmTitle: "حذف جميع الطلبات؟",
  clearAllOrdersConfirmButton: "نعم، احذف الكل!",
  clearAllOrdersSuccessTitle: "تم الحذف!",
  clearAllOrdersSuccessMessage: "تم مسح جميع الطلبات",
  refundMessage: "الطلب #{orderId}: سيتم الاسترداد قريبًا (إذا كان باي بال).",

  // AdminReservationsPage
  reservationsManagement: "إدارة الحجوزات",
  refreshReservations: "تحديث الحجوزات",
  reservationTitle: "الحجز #{reservationId}",
  tableId: "معرف الطاولة:",
  name: "الاسم:",
  date: "التاريخ:",
  numPersons: "عدد الأشخاص:",
  timeArriving: "وقت الوصول:",
  timeLeaving: "وقت المغادرة:",
  phone: "الهاتف:",
  accept: "قبول",
  reject: "رفض",
  delete: "حذف",
  previous: "السابق",
  next: "التالي",
  noReservations: "لا توجد حجوزات.",
  reservationStatusSuccess: "تم تحديث الحجز #{reservationId} إلى {status}",
  reservationStatusError: "فشل في تحديث الحجز: {error}",
  deleteReservationConfirmTitle: "هل أنت متأكد؟",
  deleteReservationConfirmText: "حذف الحجز #{reservationId}؟",
  deleteReservationConfirmButton: "نعم، احذف!",
  deleteReservationSuccessTitle: "تم الحذف!",
  deleteReservationSuccessMessage: "تم حذف الحجز #{reservationId}",
  refreshSuccessTitle: "نجاح!",
  refreshSuccessMessage: "تم تحديث الحجوزات بنجاح",
  refreshErrorTitle: "خطأ!",
  refreshErrorMessage: "فشل في جلب الحجوزات: {error}",

  // AdminPanel
  pleaseLogIn: "يرجى تسجيل الدخول.",
  noItemsInCategory: "لا توجد عناصر في هذه الفئة.",
  failedLoadCategories: "فشل في تحميل الفئات",
  failedLoadMenuItems: "فشل في تحميل عناصر القائمة",
  itemAdded: "تم إضافة العنصر!",
  itemUpdated: "تم تحديث العنصر!",
  itemDeleted: "تم حذف العنصر!",
  failedUploadImage: "فشل في رفع الصورة: {error}",
  errorSavingItem: "خطأ في حفظ العنصر: {error}",
  categoryAdded: "تم إضافة الفئة!",
  errorAddingCategory: "خطأ في إضافة الفئة",
  addItem: "إضافة عنصر",

  // CategorySelector
  menuManagement: "إدارة القائمة",
  selectCategory: "اختر فئة",

  // AdminChat
  users: "المستخدمون",
  chattingWith: "الدردشة مع {userName}",
  loadingUsers: "جارٍ تحميل المستخدمين...",
  failedLoadUsers: "فشل في تحميل المستخدمين. حاول مرة أخرى.",
  noUsersFound: "لم يتم العثور على مستخدمين.",
  selectUserToChat: "اختر مستخدمًا لبدء الدردشة.",
  // StatsSection
  totalOrders: "إجمالي الطلبات",
  totalRevenue: "إجمالي الإيرادات",
  averageOrderValue: "متوسط قيمة الطلب",
  pendingOrders: "الطلبات المعلقة",

  // OrdersList (Pagination)
  previous: "السابق",
  next: "التالي",

  // MenuItemCard
  titleEn: "العنوان (الإنجليزية)",
  titleAr: "العنوان (العربية)",
  nameEn: "الاسم (الإنجليزية)",
  nameAr: "الاسم (العربية)",
  descriptionEn: "الوصف (الإنجليزية)",
  descriptionAr: "الوصف (العربية)",
  price: "السعر",
  edit: "تعديل",
  delete: "حذف",

  // ItemModal
  addNewItem: "إضافة عنصر جديد",
  editItem: "تعديل العنصر",
  confirmDelete: "تأكيد الحذف",
  categoryEn: "الفئة (الإنجليزية)",
  categoryAr: "الفئة (العربية)",
  titleEn: "العنوان (الإنجليزية)",
  titleAr: "العنوان (العربية)",
  nameEn: "الاسم (الإنجليزية)",
  nameAr: "الاسم (العربية)",
  descriptionEn: "الوصف (الإنجليزية)",
  descriptionAr: "الوصف (العربية)",
  price: "السعر ($)",
  uploadImage: "رفع الصورة",
  addCategory: "إضافة فئة جديدة",
  categoryNameEn: "اسم الفئة (الإنجليزية)",
  categoryNameAr: "اسم الفئة (العربية)",
  add: "إضافة",
  save: "حفظ",
  cancel: "إلغاء",
  delete: "حذف",
  titleRequired: "العنوان (الإنجليزية) مطلوب",
  titleMin: "يجب أن يكون العنوان 3 أحرف على الأقل",
  titleArMin: "يجب أن يكون العنوان العربي 3 أحرف على الأقل",
  nameEnMin: "يجب أن يكون الاسم (الإنجليزية) 3 أحرف على الأقل",
  nameArMin: "يجب أن يكون الاسم (العربية) 3 أحرف على الأقل",
  descriptionMax: "الوصف لا يمكن أن يتجاوز 500 حرف",
  descArMax: "الوصف العربي لا يمكن أن يتجاوز 500 حرف",
  categoryRequired: "الفئة (الإنجليزية) مطلوبة",
  categoryArRequired: "الفئة (العربية) مطلوبة",
  priceRequired: "السعر مطلوب",
  pricePositive: "يجب أن يكون السعر رقمًا إيجابيًا",
  priceMin: "يجب أن يكون السعر $0.01 على الأقل",
  priceMax: "السعر لا يمكن أن يتجاوز $10,000",

  // OrderCard
  order: "الطلب #{orderId}",
  items: "العناصر:",
  noItems: "لا توجد عناصر",
  total: "الإجمالي:",
  placed: "تم الطلب:",
  shippingDetails: "تفاصيل الشحن:",
  city: "المدينة:",
  phone: "الهاتف:",
  details: "التفاصيل:",
  discountApplied: "تم تطبيق الخصم:",
  discountYes: "نعم (20%)",
  discountNo: "لا",
  payment: "الدفع:",
  cashOnDelivery: "الدفع عند الاستلام",
  paidPaypal: "مدفوع (باي بال)",
  trackingStatus: "حالة التتبع:",
  orderPlaced: "تم تقديم الطلب",
  processing: "قيد المعالجة",
  outForDelivery: "خارج للتوصيل",
  delivered: "تم التوصيل",
  accept: "قبول",
  reject: "رفض",
  delete: "حذف",
  statusPending: "معلق",
  statusAccepted: "مقبول",
  statusRejected: "مرفوض",
};

export default arabic;