const arabic = {
  lang: "En", // النص على الزر لتبديل اللغة
  home: "الرئيسية",
  menu: "القائمة",
  reservation: "الحجز",
  contactUs: "اتصل بنا",
  myOrders: "طلباتي",
  signIn: "تسجيل الدخول",
  register: "إنشاء حساب",
  logout: "تسجيل الخروج",
  wishlist: "المفضلة",
  cart: "عربة التسوق",
  createAccount: "إنشاء حساب",
  name: "الاسم",
  email: "البريد الإلكتروني",
  username: "اسم المستخدم",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  registerButton: "تسجيل",
  or: "أو",
  google: "جوجل",
  facebook: "فيسبوك",
  signInButton: "تسجيل الدخول", // زر تسجيل الدخول
  menuTitle: "قائمتنا",
  chickenSandwiches: "ساندويتشات الدجاج",
  beefSandwiches: "ساندويتشات اللحم",
  pizzas: "البيتزا",
  softDrinks: "عصائر فريش",
  hotDrinks: "لأصحاب المزاج",
  seeAll: "عرض الكل",
  noItems: "لا توجد عناصر متاحة",
  reservationTitle: "حجز طاولة",
  selectTable: "اختر طاولة",
  reservationForm: "نموذج الحجز",
  reservationFormTitle: "نموذج الحجز",
  selectedTable: "الطاولة المختارة",
  namePlaceholder: "الاسم",
  datePlaceholder: "التاريخ",
  numPersonsPlaceholder: "عدد الأشخاص",
  timeArrivingPlaceholder: "وقت الوصول",
  timeLeavingPlaceholder: "وقت المغادرة",
  reserveButton: "احجز",
  tableError: "يرجى اختيار طاولة.",
  tableReservedError: "هذه الطاولة محجوزة بالفعل.",
  reservationSuccess: "تم الحجز بنجاح!",
  selectTableTitle: "اختر طاولة",
  tableFor: "طاولة لـ",
  persons: "أشخاص",
  chatWith: "  الدردشة مع الإدارة",
  noMessages: "لا توجد رسائل بعد. ابدأ المحادثة!",
  typeMessage: "اكتب رسالتك...",
  sendButton: "إرسال",
  description: "desc_ar",
};

export default arabic;