const arabic = {
  lang: "En", // النص على الزر لتبديل اللغة
  home: "الرئيسية",
  menu: "القائمة",
  reservation: "الحجز",
  contactUs: "اتصل بنا",
  myOrders: "طلباتي",
  signIn: "تسجيل الدخول",
  register: "إنشاء حساب",
  logout: "تسجيل الخروج",
  wishlist: "المفضلة",
  cart: "عربة التسوق",
  createAccount: "إنشاء حساب",
  name: "الاسم",
  email: "البريد الإلكتروني",
  username: "اسم المستخدم",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  registerButton: "تسجيل",
  or: "أو",
  google: "جوجل",
  facebook: "فيسبوك",
  signInButton: "تسجيل الدخول", // زر تسجيل الدخول
  menuTitle: "قائمتنا",
  chickenSandwiches: "ساندويتشات الدجاج",
  beefSandwiches: "ساندويتشات اللحم",
  pizzas: "البيتزا",
  softDrinks: "عصائر فريش",
  hotDrinks: "لأصحاب المزاج",
  seeAll: "عرض الكل",
  noItems: "لا توجد عناصر متاحة",
  reservationTitle: "حجز طاولة",
  selectTable: "اختر طاولة",
  reservationForm: "نموذج الحجز",
  reservationFormTitle: "نموذج الحجز",
  selectedTable: "الطاولة المختارة",
  namePlaceholder: "الاسم",
  datePlaceholder: "التاريخ",
  numPersonsPlaceholder: "عدد الأشخاص",
  timeArrivingPlaceholder: "وقت الوصول",
  timeLeavingPlaceholder: "وقت المغادرة",
  reserveButton: "احجز",
  tableError: "يرجى اختيار طاولة.",
  tableReservedError: "هذه الطاولة محجوزة بالفعل.",
  reservationSuccess: "تم الحجز بنجاح!",
  selectTableTitle: "اختر طاولة",
  tableFor: "طاولة لـ",
  persons: "أشخاص",
  chatWith: "  الدردشة مع الإدارة",
  noMessages: "لا توجد رسائل بعد. ابدأ المحادثة!",
  typeMessage: "اكتب رسالتك...",
  sendButton: "إرسال",
  description: "desc_ar",
  myOrdersTitle: "طلباتي",
  sortNewest: "الأحدث أولاً",
  sortOldest: "الأقدم أولاً",
  statusAll: "الكل",
  statusPending: "قيد الانتظار",
  statusAccepted: "مقبول",
  paymentAll: "الكل",
  paymentCash: "الدفع عند الاستلام",
  paymentPayPal: "باي بال",
  noOrders: "لا توجد طلبات تطابق الفلاتر المحددة.",
  orderItems: "العناصر:",
  totalDue: "الإجمالي المستحق",
  totalPaid: "الإجمالي المدفوع",
  status: "الحالة",
  placed: "تم الطلب في",
  trackingStatus: "حالة التتبع",
  shippingDetails: "تفاصيل الشحن",
  city: "المدينة",
  phone: "الهاتف",
  details: "التفاصيل",
  trackOrder: "تتبع الطلب",
  deleteOrder: "حذف الطلب",
  myReservationsTitle: "حجوزاتي",
  pendingMessage: "في انتظار موافقة الإدارة. سيتم إخطارك بمجرد التأكيد.",
  acceptedMessage: "تم تأكيد الحجز الخاص بك! نتطلع لرؤيتك.",
  rejectedMessage: "عذرًا، لم يتم الموافقة على الحجز الخاص بك. يرجى المحاولة في وقت أو طاولة مختلفة.",
  noReservations: "لا توجد حجوزات.",
  makeNewReservation: "قم بحجز جديد",
  makeReservation: "قم بالحجز",
  tableIdLabel: "رقم الطاولة",
  nameLabel: "الاسم",
  dateLabel: "التاريخ",
  numPersonsLabel: "عدد الأشخاص",
  timeArrivingLabel: "وقت الوصول",
  timeLeavingLabel: "وقت المغادرة",
  phoneLabel: "الهاتف",
};

export default arabic;