const english = {
  lang: "Ar", // النص على الزر لتبديل اللغة
  home: "Home",
  menu: "Menu",
  reservation: "Reservation",
  contactUs: "Contact Us",
  myOrders: "My Orders",
  signIn: "Sign In",
  register: "Register",
  logout: "Log Out",
  wishlist: "Wishlist",
  cart: "Cart",
  createAccount: "Create Account",
  name: "Name",
  email: "Email",
  username: "Username",
  password: "Password",
  confirmPassword: "Confirm Password",
  registerButton: "Register",
  or: "or",
  google: "Google",
  facebook: "Facebook",
  signInButton: "Sign In", // زر تسجيل الدخول
  menuTitle: "Our Menu",
  chickenSandwiches: "Chicken Sandwiches",
  beefSandwiches: "Beef Sandwiches",
  pizzas: "Pizzas",
  softDrinks: "Soft Drinks",
  hotDrinks: "Hot Drinks",
  seeAll: "See All",
  noItems: "No items available",
  reservationTitle: "Table Reservation",
  selectTable: "Select a Table",
  reservationForm: "Reservation Form",
  reservationFormTitle: "Reservation Form",
  selectedTable: "Selected Table",
  namePlaceholder: "Name",
  datePlaceholder: "Date",
  numPersonsPlaceholder: "Number of Persons",
  timeArrivingPlaceholder: "Time of Arrival",
  timeLeavingPlaceholder: "Time of Leaving",
  reserveButton: "Reserve",
  tableError: "Please select a table.",
  tableReservedError: "This table is already reserved.",
  reservationSuccess: "Reservation successful!",
  selectTableTitle: "Select a Table",
  tableFor: "Table for",
  persons: "persons",
  chatWith: "Chat with admin",
  noMessages: "No messages yet. Start the conversation!",
  typeMessage: "Type your message...",
  sendButton: "Send",
  description: "description",
};

export default english;