const english = {
  // Existing keys from previous components
  lang: "Ar",
  home: "Home",
  menu: "Menu",
  reservation: "Reservation",
  contactUs: "Contact Us",
  myOrders: "My Orders",
  signIn: "Sign In",
  register: "Register",
  logout: "Log Out",
  wishlist: "Wishlist",
  cart: "Cart",
  chatWith: "Chat with admin",
  noMessages: "No messages yet. Start the conversation!",
  typeMessage: "Type your message...",
  sendButton: "Send",
  description: "description",
  myOrdersTitle: "My Orders",
  sortNewest: "Newest First",
  sortOldest: "Oldest First",
  statusAll: "All",
  statusPending: "Pending",
  statusAccepted: "Accepted",
  paymentAll: "All",
  paymentCash: "Cash on Delivery",
  paymentPayPal: "PayPal",
  noOrders: "No orders match the selected filters.",
  orderItems: "Items:",
  totalDue: "Total Due",
  totalPaid: "Total Paid",
  status: "Status",
  placed: "Placed",
  trackingStatus: "Tracking Status",
  shippingDetails: "Shipping Details",
  city: "City",
  phone: "Phone",
  details: "Details",
  trackOrder: "Track Order",
  deleteOrder: "Delete Order",
  myReservationsTitle: "My Reservations",
  pendingMessage: "Awaiting admin approval. You’ll be notified once confirmed.",
  acceptedMessage: "Your reservation is confirmed! We look forward to seeing you.",
  rejectedMessage: "Sorry, your reservation was not approved. Please try a different time or table.",
  noReservations: "No reservations found.",
  makeNewReservation: "Make a New Reservation",
  makeReservation: "Make a Reservation",
  tableIdLabel: "Table ID",
  nameLabel: "Name",
  dateLabel: "Date",
  numPersonsLabel: "Number of Persons",
  timeArrivingLabel: "Time Arriving",
  timeLeavingLabel: "Time Leaving",
  phoneLabel: "Phone",

  // AdminDashboard
  adminDashboard: "Admin Dashboard",
  orders: "Orders",
  reservations: "Reservations",
  menu: "Menu",
  chat: "Chat",
  logout: "Logout",
  loading: "Loading...",
  routeNotFound: "Route not found: {pathname}",
  logoutSuccess: "Logged out successfully!",
  logoutFailed: "Failed to log out: {error}",

  // AdminOrdersPage
  ordersManagement: "Orders Management",
  sort: "Sort:",
  sortNewest: "Newest First",
  sortOldest: "Oldest First",
  status: "Status:",
  statusAll: "All",
  statusPending: "Pending",
  statusAccepted: "Accepted",
  statusRejected: "Rejected",
  payment: "Payment:",
  paymentAll: "All",
  paymentCod: "Cash on Delivery",
  paymentPaypal: "PayPal",
  noOrdersFiltered: "No orders match the selected filters.",
  success: "Success!",
  error: "Error!",
  orderAccepted: "Order #{orderId} accepted",
  orderUpdateFailed: "Failed to update order: {error}",
  deleteOrderConfirmTitle: "Are you sure?",
  deleteOrderConfirmText: "Delete Order #{orderId}?",
  deleteOrderConfirmButton: "Yes, delete!",
  deleteOrderSuccessTitle: "Deleted!",
  deleteOrderSuccessMessage: "Order #{orderId} deleted",
  clearAllOrdersConfirmTitle: "Delete all orders?",
  clearAllOrdersConfirmButton: "Yes, delete all!",
  clearAllOrdersSuccessTitle: "Deleted!",
  clearAllOrdersSuccessMessage: "All orders cleared",
  refundMessage: "Order #{orderId}: Refunding soon (if PayPal).",

  // AdminReservationsPage
  reservationsManagement: "Reservations Management",
  refreshReservations: "Refresh Reservations",
  reservationTitle: "Reservation #{reservationId}",
  tableId: "Table ID:",
  name: "Name:",
  date: "Date:",
  numPersons: "Number of Persons:",
  timeArriving: "Time Arriving:",
  timeLeaving: "Time Leaving:",
  phone: "Phone:",
  accept: "Accept",
  reject: "Reject",
  delete: "Delete",
  previous: "Previous",
  next: "Next",
  noReservations: "No reservations found.",
  reservationStatusSuccess: "Reservation #{reservationId} {status}",
  reservationStatusError: "Failed to update reservation: {error}",
  deleteReservationConfirmTitle: "Are you sure?",
  deleteReservationConfirmText: "Delete Reservation #{reservationId}?",
  deleteReservationConfirmButton: "Yes, delete!",
  deleteReservationSuccessTitle: "Deleted!",
  deleteReservationSuccessMessage: "Reservation #{reservationId} deleted",
  refreshSuccessTitle: "Success!",
  refreshSuccessMessage: "Reservations refreshed successfully",
  refreshErrorTitle: "Error!",
  refreshErrorMessage: "Failed to fetch reservations: {error}",

  // AdminPanel
  pleaseLogIn: "Please log in.",
  noItemsInCategory: "No items found in this category.",
  failedLoadCategories: "Failed to load categories",
  failedLoadMenuItems: "Failed to load menu items",
  itemAdded: "Item added!",
  itemUpdated: "Item updated!",
  itemDeleted: "Item deleted!",
  failedUploadImage: "Failed to upload image: {error}",
  errorSavingItem: "Error saving item: {error}",
  categoryAdded: "Category added!",
  errorAddingCategory: "Error adding category",
  addItem: "Add Item",

  // CategorySelector
  menuManagement: "Menu Management",
  selectCategory: "Select Category",

  // AdminChat
  users: "Users",
  chattingWith: "Chatting with {userName}",
  loadingUsers: "Loading users...",
  failedLoadUsers: "Failed to load users. Please try again.",
  noUsersFound: "No users found.",
  selectUserToChat: "Select a user to start chatting.",

  // StatsSection
  totalOrders: "Total Orders",
  totalRevenue: "Total Revenue",
  averageOrderValue: "Average Order Value",
  pendingOrders: "Pending Orders",

  // OrdersList (Pagination)
  previous: "Previous",
  next: "Next",

  // MenuItemCard
  titleEn: "Title (EN)",
  titleAr: "Title (AR)",
  nameEn: "Name (EN)",
  nameAr: "Name (AR)",
  descriptionEn: "Description (EN)",
  descriptionAr: "Description (AR)",
  price: "Price",
  edit: "Edit",
  delete: "Delete",

  // ItemModal
  addNewItem: "Add New Item",
  editItem: "Edit Item",
  confirmDelete: "Confirm Delete",
  categoryEn: "Category (English)",
  categoryAr: "Category (Arabic)",
  titleEn: "Title (English)",
  titleAr: "Title (Arabic)",
  nameEn: "Name (English)",
  nameAr: "Name (Arabic)",
  descriptionEn: "Description (English)",
  descriptionAr: "Description (Arabic)",
  price: "Price ($)",
  uploadImage: "Upload Image",
  addCategory: "Add New Category",
  categoryNameEn: "Category Name (English)",
  categoryNameAr: "Category Name (Arabic)",
  add: "Add",
  save: "Save",
  cancel: "Cancel",
  delete: "Delete",
  titleRequired: "Title (English) is required",
  titleMin: "Title must be at least 3 characters",
  titleArMin: "Arabic title must be at least 3 characters",
  nameEnMin: "Name (English) must be at least 3 characters",
  nameArMin: "Arabic name must be at least 3 characters",
  descriptionMax: "Description cannot exceed 500 characters",
  descArMax: "Arabic description cannot exceed 500 characters",
  categoryRequired: "Category (English) is required",
  categoryArRequired: "Category (Arabic) is required",
  priceRequired: "Price is required",
  pricePositive: "Price must be a positive number",
  priceMin: "Price must be at least $0.01",
  priceMax: "Price cannot exceed $10,000",

  order: "Order #{orderId}",
  items: "Items:",
  noItems: "No items",
  total: "Total:",
  placed: "Placed:",
  shippingDetails: "Shipping Details:",
  city: "City:",
  phone: "Phone:",
  details: "Details:",
  discountApplied: "Discount Applied:",
  discountYes: "Yes (20%)",
  discountNo: "No",
  payment: "Payment:",
  cashOnDelivery: "Cash on Delivery",
  paidPaypal: "Paid (PayPal)",
  trackingStatus: "Tracking Status:",
  orderPlaced: "Order Placed",
  processing: "Processing",
  outForDelivery: "Out for Delivery",
  delivered: "Delivered",
  accept: "Accept",
  reject: "Reject",
  delete: "Delete",
  statusPending: "Pending",
  statusAccepted: "Accepted",
  statusRejected: "Rejected",
};


export default english;